//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Company()
        {
            this.Departments = new HashSet<Department>();
        }
    
        public long Id { get; set; }
        public string CompanyName { get; set; }
        public string Address { get; set; }
        public Nullable<double> ExchageRateUSD { get; set; }
        public Nullable<bool> IsMaintenance { get; set; }
        public string Hotline { get; set; }
        public string CallCenter { get; set; }
        public string EmailAddress { get; set; }
        public string FacebookPage { get; set; }
        public string YoutubeChanel { get; set; }
        public string TwitterPage { get; set; }
        public string GoogleAnalytics { get; set; }
        public string ImageUrlLogo { get; set; }
        public string ImageUrlIcon { get; set; }
        public string TaxCode { get; set; }
        public string Content { get; set; }
        public string GoogleMapAPI { get; set; }
        public Nullable<int> NumberOfExpirationDates { get; set; }
        public Nullable<int> DefaulPageSize { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Department> Departments { get; set; }
    }
}
