//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Estate()
        {
            this.Comments = new HashSet<Comment>();
            this.Estate_Images = new HashSet<Estate_Images>();
        }
    
        public long Id { get; set; }
        public Nullable<long> Estate_TypeId { get; set; }
        public Nullable<long> Estate_GroupId { get; set; }
        public Nullable<long> Estate_StatusId { get; set; }
        public Nullable<long> Estate_ProjectId { get; set; }
        public string ImageUrl { get; set; }
        public Nullable<long> AccountId { get; set; }
        public Nullable<long> TownId { get; set; }
        public Nullable<int> SaleRent { get; set; }
        public string Code { get; set; }
        public Nullable<double> Square { get; set; }
        public Nullable<double> SalePrice { get; set; }
        public Nullable<long> SaleUnitId { get; set; }
        public Nullable<double> RentPrice { get; set; }
        public Nullable<long> RentUnitId { get; set; }
        public string HouseNo { get; set; }
        public string LotId { get; set; }
        public string Mobile { get; set; }
        public string OwnerName { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string Note { get; set; }
        public Nullable<bool> IsHot { get; set; }
        public string LogBy { get; set; }
        public string Map { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public Nullable<long> ProvinceId { get; set; }
        public Nullable<long> DistrictId { get; set; }
        public Nullable<long> WardId { get; set; }
        public Nullable<long> StreetId { get; set; }
        public string Estate_Address { get; set; }
        public string LinkVideoYoutube { get; set; }
        public string Link360 { get; set; }
        public Nullable<int> Number_Lot { get; set; }
        public Nullable<int> Number_Paper { get; set; }
        public Nullable<float> Frontispiece { get; set; }
        public Nullable<float> LotLength { get; set; }
        public Nullable<bool> ExpandAfter { get; set; }
        public Nullable<int> Number_Bedrooms { get; set; }
        public Nullable<int> Number_Livingrooms { get; set; }
        public Nullable<int> Number_Floors { get; set; }
        public Nullable<int> Number_Toilets { get; set; }
        public Nullable<int> DriectionOfTheHouse { get; set; }
        public Nullable<double> LandArea { get; set; }
        public Nullable<float> AreaOffUse { get; set; }
        public Nullable<float> ConstructionArea { get; set; }
        public Nullable<float> FrontOfHouse { get; set; }
        public Nullable<float> AlleyOfHouse { get; set; }
        public Nullable<long> Certificate_TypeId { get; set; }
        public string ShotDescription { get; set; }
        public string FullDescription { get; set; }
        public Nullable<int> Views { get; set; }
        public Nullable<bool> IsOutSide { get; set; }
        public Nullable<int> DeviceType { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string Active360Folders { get; set; }
    
        public virtual Account Account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual District District { get; set; }
        public virtual Estate_Groups Estate_Groups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Estate_Images> Estate_Images { get; set; }
        public virtual Estate_Projects Estate_Projects { get; set; }
        public virtual Estate_Statuses Estate_Statuses { get; set; }
        public virtual Estate_Types Estate_Types { get; set; }
        public virtual Province Province { get; set; }
        public virtual RentUnit RentUnit { get; set; }
        public virtual SaleUnit SaleUnit { get; set; }
        public virtual Street Street { get; set; }
        public virtual Town Town { get; set; }
        public virtual Ward Ward { get; set; }
        public virtual Certificate_Types Certificate_Types { get; set; }
    }
}
