//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estate_Images
    {
        public long ItemId { get; set; }
        public Nullable<int> Type { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Modified { get; set; }
        public string Alias { get; set; }
        public string MetaKeywords { get; set; }
        public string MetaDescription { get; set; }
        public string MetaTitle { get; set; }
        public bool IsDelete { get; set; }
        public string Title { get; set; }
        public string Url { get; set; }
        public Nullable<long> EstateId { get; set; }
    
        public virtual Estate Estate { get; set; }
    }
}
