//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public long ProductId { get; set; }
        public Nullable<long> CategoryId { get; set; }
        public Nullable<long> VendorId { get; set; }
        public Nullable<long> AlbumId { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public string Image { get; set; }
        public Nullable<double> BasePrice { get; set; }
        public Nullable<double> SalePrice { get; set; }
        public string Detail { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string MetaKeywords { get; set; }
        public string MetaDescription { get; set; }
        public string MetaTitle { get; set; }
        public string Alias { get; set; }
        public Nullable<bool> AllowComments { get; set; }
        public string Tags { get; set; }
    
        public virtual Album Album { get; set; }
        public virtual Category Category { get; set; }
        public virtual Vendor Vendor { get; set; }
    }
}
