//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public Account()
        {
            this.AccountRoles = new HashSet<AccountRole>();
            this.Comments = new HashSet<Comment>();
            this.LoginLogs = new HashSet<LoginLog>();
            this.SanPhams = new HashSet<SanPham>();
            this.ThongBaos = new HashSet<ThongBao>();
        }
    
        public long AccountId { get; set; }
        public Nullable<long> DepartmentId { get; set; }
        public string UserName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> LastSignIn { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string Image { get; set; }
        public string Detail { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual ICollection<AccountRole> AccountRoles { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<LoginLog> LoginLogs { get; set; }
        public virtual ICollection<SanPham> SanPhams { get; set; }
        public virtual ICollection<ThongBao> ThongBaos { get; set; }
    }
}
