//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        public long ArticleId { get; set; }
        public string Title { get; set; }
        public string Image { get; set; }
        public Nullable<long> CategoryId { get; set; }
        public string Short { get; set; }
        public string Contents { get; set; }
        public string Alias { get; set; }
        public Nullable<bool> AllowComments { get; set; }
        public string MetaKeywords { get; set; }
        public string MetaDescription { get; set; }
        public string MetaTitle { get; set; }
        public string Tags { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<long> CreateBy { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
