//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.Articles = new HashSet<Article>();
            this.Products = new HashSet<Product>();
        }
    
        public long CategoryId { get; set; }
        public Nullable<long> CategoryTypeId { get; set; }
        public string CategoryName { get; set; }
        public Nullable<int> CateLevel { get; set; }
        public Nullable<long> ParentCategoryId { get; set; }
        public string Image { get; set; }
        public long GroupCategoryId { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public string MetaTitle { get; set; }
        public string Alias { get; set; }
        public string MetaKeywords { get; set; }
        public string MetaDescription { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<int> OrderNumber { get; set; }
    
        public virtual ICollection<Article> Articles { get; set; }
        public virtual CategoryType CategoryType { get; set; }
        public virtual GroupCategory GroupCategory { get; set; }
        public virtual ICollection<Product> Products { get; set; }
    }
}
