//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public long Id { get; set; }
        public string Contents { get; set; }
        public Nullable<long> CreateById { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<long> SanPhamId { get; set; }
        public Nullable<long> ThongBaoId { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual SanPham SanPham { get; set; }
        public virtual ThongBao ThongBao { get; set; }
    }
}
