//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        public SanPham()
        {
            this.Comments = new HashSet<Comment>();
        }
    
        public long Id { get; set; }
        public Nullable<long> AccountId { get; set; }
        public Nullable<long> KhuPhoId { get; set; }
        public Nullable<int> BanChoThue { get; set; }
        public string KyHieu { get; set; }
        public string DienTich { get; set; }
        public Nullable<double> GiaBan { get; set; }
        public Nullable<long> DonViBanId { get; set; }
        public Nullable<double> GiaThue { get; set; }
        public Nullable<long> DonViThueId { get; set; }
        public string SoNha { get; set; }
        public string MaLo { get; set; }
        public string SoDienThoai { get; set; }
        public string TenChuNha { get; set; }
        public Nullable<System.DateTime> NgayNhap { get; set; }
        public Nullable<System.DateTime> NgaySua { get; set; }
        public string GhiChu { get; set; }
        public Nullable<bool> IsHot { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string LogBy { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual DonViBan DonViBan { get; set; }
        public virtual DonViThue DonViThue { get; set; }
        public virtual KhuPho KhuPho { get; set; }
    }
}
