//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongBao
    {
        public ThongBao()
        {
            this.Comments = new HashSet<Comment>();
        }
    
        public long Id { get; set; }
        public string TieuDe { get; set; }
        public string NoiDung { get; set; }
        public Nullable<long> AccountId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<bool> AllowComment { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
    }
}
